---
title: "大创最优组队方案及模型"
author: "沈雨薇 2016200620"
date: "2019年3月5日"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

## 一、问题背景

&emsp;&emsp; 随着创新、创业热度和重要性的不断提高，大学生创新创业训练计划也受到了越来越多的关注。在一年一度的大学生创新创业训练计划（以下简称“大创”）中，大学本科生需要进行组队来参与项目立项报告的撰写和调研活动。如何能合理地进行组队，从而完成立项报告，这是我们需要关注的问题。

假设有来自5个学院的300名学生要进行大创组队，每个队伍有n名学生($n \le 5$)，其中包含一个项目负责人，需要根据项目负责人所在的院系进行名额分配。每个学院的项目根据报名人数，选出前50%或者前3个队伍。当报名队伍数量$\le 6$时，前3只队伍出线，报名队伍数量$>6$时，50%的队伍数量（向下取整后）出线。进行组队主要考虑的条件分别有：队员所在学院、平均成绩、过往经验、实践能力（计算机水平和调研能力）、写作水平（语言表达能力）、领导与组织能力、社会资源等7个指标。由于大创是院内竞争，故学生在自由组队的情况下，会按照各自的能力对组队队员进行双向选择，使队伍的综合得分尽量高；在均衡的状态下，各个队伍的竞争力相近。

我们首先在一个相对简单的情况下考虑，然后再将其拓展到较复杂的情况。本文主要探讨所有学生可以在两个学院报名，每个学院的参赛队伍固定，每个参赛队伍人数小于等于5，且在近似均衡状态（每个学院内部队伍间竞争力差异最小）下的组队方案。


## 二、模型假设

1. 每个学生只能参加一个大创组队
2. 每个队伍里学生人数$\le 5$
3. 假设问题中队员的基本条件充分反映了队员的真实水平和能力
4. 学员的信息都是完全信息
5. 学员的能力相不干扰，取队员的能力和作为队伍的单项能力


## 三、模型的建立

&emsp;&emsp;假设共有n名学生是潜在的大创组队队员，每个学院的队伍数量固定为M，在不考虑来源学院的情况下，第x名学生的剩余6个指标用$q_{xi},i\in\{1,2,...6\}$来表示,假设每个指标的权重相同。不妨用$G_{Dj}$来代表学院D中，第j个队伍的整体水平，用$G_{Djm}$来代表学院D中，队伍编号为$j$的队伍的第$m$项指标得分，其中$m \in \{1,2,3,4,5,6\}$。在当前$n=300$的情况下，共应该有队伍数量为$60$只，每个学院队伍数量为$30$只。不妨用$x_{ij}$变量代表第i个学生是否参加第$j$个队伍的示性函数。学生可以在a,b两个学院报名大创



$$
x_{Dij}=\left \{\begin{array}
\ 0 & 第i名队员不参加第j个组队\\
1  & 第i名队员不参加第j个组队
\end{array}\right.
i \in \{1,2,...n\};j \in \{1,2,...M\};D \in \{a,b\}
$$

&emsp;&emsp;显然，由假设，有
$$G_{Djm}= \sum q_{km},m \in \{1,2,3,4,5,6\}\\
G_{Dj}=\frac{1}{6}\sum_{m=1}^6G_{Djm}\\
G_{j}=\frac{1}{6}\sum_{m=1}^{6}\sum q_{km},q_{km}代表第k个人的第m项分数
$$
由于每个队员只能参加一个组队，故
$$
\sum \limits_{j=1}^{M}x_{Dij} \le
1, \forall i \in \{1,2,...n\}
$$
由于每个队伍队员不多于5名，故
$$
\sum \limits_{i=1}^{n}x_{Dij}\le5, \forall j \in \{1,2,...M\},D\in \{a,b\}
$$
目标是让每个每个学院内队伍之间的差距最小,可以表示为学院中每队的竞争力尽可能大,同时小于总体竞争力的$\frac{1}{M}$
可以表达成
$$
Max(G_{Di})\\
st. G_{Di}\le \frac{1}{M}\sum G_{Di}, i\in \{1,2,...M\}
$$


## 模型的求解
&emsp;&emsp;不太会_(:з」∠)_

## 模型的拓展与思考
&emsp;&emsp;可以考虑将学院从2个学院拓展到多个学院；在本模型中，每个学院报名的队伍数量是固定的，但是在实际情况下，每个学院报名的队伍数量是不固定的；变更队伍竞争力的计算方式，在本模型中，队伍的单项竞争力是所有人的竞争力之和，故5人队比3人队竞争力高，但是人多的队伍人均项目资金会少，所以在自由组队的情况下，5人队未必是最优的选择，可以增加一个和队伍人数有关的惩罚因子或者增加新的目标函数，将项目人均资金也考虑在内。此外，可以将队伍竞争力表示为非线性函数、分段函数等，并对团队中每个成员的分数进行加权处理，例如组队负责人的权重最高，其他人均分 ，并可以将每个指标按照重要性程度进行加权，例如平均成绩的权重最高，其他的权重稍低,以此来完善模型。

&emsp;&emsp;此外，由于定义了不同学院队伍出线名额，可以引入风险的概念，让队伍根据历史信息和各个学院人口比例等先验信息进行风险预测，从而选择在什么学院报名，使出线概率最大化。首先，确定初步组队人选，其次，根据当前团队组成，确定风险最小的学院，然后，在该风险计算方式下选择让风险减少最大的团队成员，直到人数到达5人或者风险不减，这样即可实现自由组队的动态模拟。

